version: '3'

services:
  listing:
    container_name: listing-service
    build: ./services/listings
    ports:
      - "6000:6000"
    networks:
      - app-network
  
  user:
    container_name: user-service
    build: ./services/users
    ports:
      - "8000:8000"
    networks:
      - app-network
  
  public-api:
    container_name: public-api-service
    build: ./services/public-api
    ports:
      - "7000:7000"
    environment:
      - LISTINGS_URL=http://listing:6000/listings
      - USERS_URL=http://user:8000/users
    depends_on:
      listing:
        condition: service_started
      user:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
